apiVersion: v1
kind: ConfigMap
metadata:
  namespace: linky
  name: mysql-config
  labels:
    app: mysql
data:
  my.cnf: |
    [mysqld]
    default-storage-engine=INNODB
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    max_connections=200
    bind-address=0.0.0.0
    
    # 성능 최적화
    innodb_buffer_pool_size=512M
    innodb_log_file_size=128M
    innodb_flush_log_at_trx_commit=1
    innodb_file_per_table=1
    
    # 타임존 설정
    default-time-zone='+09:00'
    
    [mysql]
    default-character-set=utf8mb4
    
    [client]
    default-character-set=utf8mb4
