apiVersion: v1
kind: Service
metadata:
  namespace: linky
  name: mysql-service
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 32306
  type: NodePort
