apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: linky
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage