apiVersion: v1
kind: Service
metadata:
  name: redis-stack-service
  namespace: linky
  labels:
    app: redis-stack
spec:
  selector:
    app: redis-stack
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: redis-ui
      port: 8001
      targetPort: 8001
      nodePort: 30001
  type: NodePort
