apiVersion: v1
kind: ConfigMap
metadata:
  namespace: linky
  name: linky-backend-properties
  labels:
    part-of: k8s-linky
    component: backend-server
    name: linky-backend
    version: 1.0.0
    managed-by: kubectl
data:
  spring_profiles_active: "prod"