pipeline {
    agent none  // 전체에는 agent 없음

    environment {
        GITLAB_URL = "https://lab.ssafy.com/s13-webmobile3-sub1/S13P11C102.git"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKER_IMAGE = "parkheejun/linky-backend"
        IMAGE_TAG = "1.0.0"
    }

    stages {
        stage('릴리즈파일 체크아웃') {
            agent any
            steps {
                git branch: 'feature/deploy',
                    credentialsId: 'gitlab-credentials',
                    url: "${GITLAB_URL}"

                // 작업 공간을 다음 스테이지에서 사용할 수 있도록 저장
                stash includes: '**/*', name: 'source-code'
            }
        }

        stage('소스 빌드') {
            agent {
                docker {
                    image 'gradle:8-jdk17'
                }
            }
            steps {
                unstash 'source-code'
                sh "chmod +x ./apps/backend/gradlew"
                sh "./apps/backend/gradlew clean build --no-daemon"

                // 빌드 결과물 저장
                stash includes: 'apps/backend/build/**/*', name: 'build-artifacts'
            }
        }

        stage('Docker 이미지 빌드 및 배포') {
            agent {
                docker {
                    image 'docker:28.3.3'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                unstash 'source-code'
                unstash 'build-artifacts'

                // Docker 빌드
                sh "docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} ."
                sh "docker tag ${DOCKER_IMAGE}:${IMAGE_TAG} ${DOCKER_IMAGE}:latest"

                // Docker Hub 푸시
                sh "echo \$DOCKERHUB_CREDENTIALS_PSW | docker login -u \$DOCKERHUB_CREDENTIALS_USR --password-stdin"
                sh "docker push ${DOCKER_IMAGE}:${IMAGE_TAG}"
                sh "docker push ${DOCKER_IMAGE}:latest"
            }
        }

        stage('쿠버네티스 배포') {
            agent {
                docker {
                    image 'bitnami/kubectl:latest'
                }
            }
            steps {
                unstash 'source-code'
                sh "kubectl apply -f ./k8s/app/namespace.yaml"
                sh "kubectl apply -f ./k8s/app/configmap.yaml"
                sh "kubectl apply -f ./k8s/app/secret.yaml"
                sh "kubectl apply -f ./k8s/app/service.yaml"
                sh "kubectl apply -f ./k8s/app/deployment.yaml"
            }
        }
    }

    post {
        always {
            node('') {
                sh "docker rmi ${DOCKER_IMAGE}:${IMAGE_TAG} || true"
                sh "docker rmi ${DOCKER_IMAGE}:latest || true"
                sh "docker logout || true"
            }
        }
    }
}