spring:
  application:
    name: linky

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  hikari:
    minimum-idle: 3
    maximum-pool-size: 5
    connection-timeout: 600000
    idle-timeout: 300000

  logging:
    level:
      org.springframework.web: INFO
      com.example: DEBUG

  mybatis:
    mapper-locations: classpath:/mappers/**/*.xml
    type-aliases-package: com.link.api.*.entity

    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
