apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linky-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://lab.ssafy.com/s13-webmobile3-sub1/S13P11C102.git
    targetRevision: HEAD
    path: k8s
    directory:
      exclude: "ingress.yaml"  # ingress 파일 제외
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true