server:
  address: 0.0.0.0
  port: 8080

  servlet:
    session:
      cookie:
        name: LINKY_SESSION
        http-only: true
        secure: false
        same-site: lax
        max-age: 7200
        path: /
      timeout: 120m

spring:
  application:
    name: linky

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

    postgres:
      driver-class-name: org.postgresql.Driver
      url: ${POSTGRES_DB_URL}
      username: ${POSTGRES_DB_USERNAME}
      password: ${POSTGRES_DB_PASSWORD}

  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    connection-timeout: 600000
    idle-timeout: 300000

  servlet:
    multipart:
      file-size-threshold: 10MB
      location: ${user.home}/uploads
      max-file-size: 10MB
      max-request-size: 50MB

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

  ai:
    openai:
      chat:
        options:
          model: gpt-4.1-nano
          temperature: 0.7
          max-tokens: 4096
      api-key: ${GMS_API_KEY}
      base-url: ${GMS_API_URL}

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.linky.api.*.entity

sms:
  api-key: ${SMS_API_KEY}
  secret-key: ${SMS_SECRET_KEY}

openvidu:
  url: ${OPENVIDU_API_URL}
  secret: ${OPENVIDU_API_SECRET}
