grpc:
  server:
    port: 50051

spring:
  application:
    name: linky

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  hikari:
    minimum-idle: 3
    maximum-pool-size: 5
    connection-timeout: 600000
    idle-timeout: 300000

  logging:
    level:
      org.springframework.web: INFO
      com.example: DEBUG

    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  servlet:
    multipart:
      file-size-threshold: 10MB
      location: ${user.home}/uploads
      max-file-size: 10MB
      max-request-size: 50MB

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  data:
    redis:
      password: 1234
      host: localhost
      port: 6379

  mqtt:
    broker-url: tcp://localhost:1883
    client-id: linky-server
    topic: linky/robot


mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.linky.api.*.entity

sms:
  api-key: ${SMS_API_KEY}
  secret-key: ${SMS_SECRET_KEY}
