spring:
  config:
    activate:
      on-profile: prod

  logging:
    level:
      org.springframework.ai: INFO
      org.springframework.web.client: WARN
      com.linky.api.aichat: INFO
      root: WARN

    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mqtt:
    broker-url: ${MOSQUITTO_URL}
    client-id: ${MOSQUITTO_CLIENT_ID}
    topic: ${MOSQUITTO_CLIENT_ID}

ocr:
  server:
    address: 172.29.121.149