spring:
  config:
    activate:
      on-profile: dev

  logging:
    level:
      org.springframework.ai: DEBUG
      org.springframework.web.client: DEBUG
      com.linky.api.aichat: DEBUG

    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mqtt:
    broker-url: ${MOSQUITTO_URL}
    client-id: ${MOSQUITTO_CLIENT_ID}
    topic: ${MOSQUITTO_CLIENT_ID}