grpc:
  server:
    address: 0.0.0.0
    port: 50051

server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: linky

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

    postgres:
      driver-class-name: org.postgresql.Driver
      url: ${POSTGRES_DB_URL}
      username: ${POSTGRES_DB_USERNAME}
      password: ${POSTGRES_DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
    open-in-view: false

  hikari:
    minimum-idle: 3
    maximum-pool-size: 5
    connection-timeout: 600000
    idle-timeout: 300000

  logging:
    level:
      org.springframework.ai: DEBUG
      org.springframework.web.client: DEBUG
      com.linky.api.aichat: DEBUG

    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  servlet:
    multipart:
      file-size-threshold: 10MB
      location: ${user.home}/uploads
      max-file-size: 10MB
      max-request-size: 50MB

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  data:
    redis:
      password: 1234
      host: localhost
      port: 6379

  mqtt:
    broker-url: tcp://192.168.100.83:1883
    client-id: linky-server
    topic: linky/robot

  ai:
    openai:
      chat:
        options:
          model: gpt-4.1-nano
          temperature: 0.7
          max-tokens: 4096
      api-key: ${GMS_API_KEY}
      base-url: https://gms.ssafy.io/gmsapi/api.openai.com/v1/chat/completions

  task:
    scheduling:
      enabled: true
      pool:
        size: 5

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.linky.api.*.entity

sms:
  api-key: ${SMS_API_KEY}
  secret-key: ${SMS_SECRET_KEY}

openvidu:
  url: https://i13c102.p.ssafy.io:443
  secret: linky1234
