apiVersion: v1
kind: Service
metadata:
  namespace: linky
  name: linky-backend
  labels:
    part-of: k8s-linky
    component: backend-server
    name: linky-backend
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-linky
    component: backend-server
    name: linky-backend
    blue-green-no: "1"
  ports:
    - port: 80
      targetPort: http
      nodePort: 32214
  type: NodePort