apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: linky
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      nodePort: 30007
  type: NodePort
